name: Deployment workflow

on:
  push:
    branches:
      - main
  workflow_call:

jobs:
  staging:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        environment:
          - staging
          - production
      max-parallel: 1

    environment: ${{ matrix.environment }}

    env:
      DOCKER_TAG: ${{ matrix.environment == 'production' && 'latest' || 'edge' }}
      DOCKER_REGISTRY: ghcr.io
      DOCKER_NAMESPACE: ${{ github.repository_owner }}
      DOCKER_EXTRA_ARGS: --label org.opencontainers.image.source=https://github.com/${{ github.repository }} --cache-from type=gha,mode=max --cache-to type=gha,mode=max

    steps:
      - uses: actions/checkout@v4
      - uses: kir-dev/automations/actions/infra-build-images@feat/build-docker-actions
        with:
          registry: ${{ env.DOCKER_NAMESPACE }}
          namespace: ${{ env.DOCKER_NAMESPACE }}
          docker-tag: ${{ env.DOCKER_TAG }}
          extra-args: --push ${{ env.DOCKER_EXTRA_ARGS }}
